CREATE TABLE Services (
ID INT PRIMARY KEY, 
ServiceName VARCHAR(50) NOT NULL,
ServiceCode VARCHAR(50) NOT NULL,
RentalTime VARCHAR(50) NOT NULL,
CostPerHour MONEY NOT NULL)

CREATE TABLE Clients (
Surname VARCHAR (30) NOT NULL,
Name VARCHAR(30) NOT NULL,
Patronymic VARCHAR(30) NOT NULL,
Code INT PRIMARY KEY,
PassportData CHAR(50) NOT NULL,
DateOfBirth DATE NOT NULL,
Adress TEXT NOT NULL,
Email VARCHAR(50) NOT NULL,
Password VARCHAR(20) NOT NULL)

CREATE TABLE Statuses (
ID INT PRIMARY KEY IDENTITY,
Status VARCHAR(20) NOT NULL)

CREATE TABLE Orders (
ID INT PRIMARY KEY IDENTITY,
OrderCode VARCHAR(50) NOT NULL,
CreateDate DATE NOT NULL,
OrderTime TIME NOT NULL,
ClientCode INT NOT NULL FOREIGN KEY REFERENCES Clients(Code),
StatusId INT NOT NULL FOREIGN KEY REFERENCES Statuses(ID),
CloseDate DATE NULL,
RentalTime VARCHAR(50) NOT NULL)

CREATE TABLE Posts ( 
ID INT PRIMARY KEY,
Title VARCHAR(20) NOT NULL)

CREATE TABLE Staff (
ID INT PRIMARY KEY,
Surname VARCHAR (30) NOT NULL,
Name VARCHAR(30) NOT NULL,
Patronymic VARCHAR(30) NOT NULL,
Login VARCHAR(50) NOT NULL,
Passwrod VARCHAR(50) NOT NULL,
PostId INT NOT NULL FOREIGN KEY REFERENCES Posts(ID),
LastAuth DATETIME NOT NULL,
AuthType VARCHAR(20) NOT NULL,
Photo IMAGE NULL)

INSERT INTO Posts (ID, Title)
VALUES ('1', 'Администратор'),
	   ('2', 'Старший смены'),
	   ('3', 'Продавец')